name: Merge upstream branches
on:
  schedule:
     # actually, ~5 minutes is the highest
     # effective frequency you will get
    - cron:  '* */1 * * *'
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          # git config --global user.name 'Alex-NRCan'
          # git config --global user.email 'alexandre.roy@nrcan-rncan.gc.ca'

          git remote add upstream https://github.com/geopython/pygeoapi.git
          git fetch upstream

          # "git checkout master" is unnecessary, already here by default
          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v2 can also be instructed
                                # to fetch all git depth right from the start)

          # Synch/Merge
          git checkout develop
          git merge --no-edit upstream/master
          git push
      - name: Check if failed
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          # mail server settings
          server_address: ${{ secrets.EMAIL_HOST }}
          server_port: ${{ secrets.EMAIL_PORT }}
          # user credentials
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          # email subject
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          # email body as text
          body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
          # comma-separated string, send email to
          to: alexandre.roy@nrcan-rncan.gc.ca
          # from email name
          from: John Doe
